### ISSUE TITLE
Unexpected behavior of article titles

### ISSUE THREAD

**Issue by MurichAJ** [ionic-team/ionic-docs#1370] opened 2020-04-20 14:15 UTC
When you **tap and/or highlight** article title and go to another page using the side menu, you have an article you need but the title will be previously. And this first title name that you taped stay unless you reload a page.

**To reproduce**
1. Go to 'https://ionicframework.com/docs/developing/previewing'
2. Click on 'Previewing' - it is the title in the article
3. Go to another page in docs using the side menu
4. See the incorrect name in the title

**Expected behavior**
Title name might be the same as the side menu

**Screenshots**
[FireShot Capture 004 - Scaffolding - Ionic Documentation - ionicframework.com.pdf](https://github.com/ionic-team/ionic-docs/files/4504020/FireShot.Capture.004.-.Scaffolding.-.Ionic.Documentation.-.ionicframework.com.pdf)
[FireShot Capture 005 - Previewing - Ionic Documentation - ionicframework.com.pdf](https://github.com/ionic-team/ionic-docs/files/4504023/FireShot.Capture.005.-.Previewing.-.Ionic.Documentation.-.ionicframework.com.pdf)

**Browser and OS**
 - OS: [Ubuntu 18.04]
 - Browser: [chrome]
 - Version: [Version 81.0.4044.113 (Official Build) (64-bit)]

**Additional context**
In the browser, I`ve many extensions that work with text. For example Google Translate, TransOver

**Update**
The same behavior I see when I click on the article`s text and then go to another page by the side menu.

**Comment by rtpHarry** [comment] 2020-04-24 23:24
I can't recreate it with the Previewing page but I'm getting it when moving between Gestures and Animations.

It doesn't happen every time. 

If you start on Gestures or Animations as a fresh page it works ok.

If you click into either Gestures or Animations and then any other page it seems to be fine.

If you click into Gestures | Animations and then to Animations | Gestures the whole thing breaks down.

The next prev section starts point at the wrong place, the left nav updates, the contents doesn't.

My guess was that it was maybe something to do with a duplicate anchor tag being used but I couldn't find anything like that. Strange behaviour!

**Comment by brandyscarney** [comment] 2020-04-30 15:18
I've also run into this with Gestures / Animations. cc @liamdebeasi @perrygovier

**Comment by liamdebeasi** [comment] 2020-04-30 15:35
For the Animation/Gesture reproduction I do see the following errors in my console:

`TypeError: Cannot read property 'insertBefore' of null`

and occasionally:

`Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null`

The `insertBefore` error seems to reference https://github.com/ionic-team/stencil/blob/master/src/runtime/vdom/vdom-render.ts#L299 but this could just be a misconfiguration in the docs not necessarily a bug in Stencil.

**Comment by amandaejohnston** [comment] 2023-01-13 17:20
It looks like this has since been resolved; I'm unable to replicate the issue on the latest version of the docs. Due to this and the age of this issue, I'm going to go ahead and close this out, but please let me know if any of you are still able to reproduce. A screencast may be useful as well.

**Closed by amandaejohnston** 2023-01-13 17:20 UTC
Labels: triage
