### ISSUE TITLE
content: RTL support Docs doesn't exist

### ISSUE THREAD

**Issue by FranciskoNeves** [ionic-team/ionic-docs#2818] opened 2023-03-10 09:53 UTC
### URL

https://ionicframework.com/docs/v5/layout/rtl

### Issue Description

I can't find a proper docs of RTL support in Ionic 4 and above. 

This pages has a TODO:
https://ionicframework.com/docs/v4/layout/rtl
https://ionicframework.com/docs/v5/layout/rtl

This page doesn't even exist:
https://ionicframework.com/docs/v6/layout/rtl

**Comment by amandaejohnston** [comment] 2023-03-10 15:12
Thank you for the report. Ionic supports RTL automatically, so we haven't added a dedicated docs page because there isn't much to say. Was there any particular question you were trying to answer?

**Comment by FranciskoNeves** [comment] 2023-03-10 15:30
I understand, but anyway I think there should be some information like the one you gave me, and for example the correct way to apply RTL to the ion-menu component that I needed to use a workaround, and maybe other small things.

**Comment by amandaejohnston** [comment] 2023-03-13 14:06
Could you give more details on the workaround and other small things? It's possible there was a bug or two in there, or at least something that should be documented on the component-specific pages.

**Comment by amandaejohnston** [comment] 2023-03-13 16:56
Both of those component issues sound like bugs we should just fix, rather than documentation problems. We have this issue for `ion-menu`: https://github.com/ionic-team/ionic-framework/issues/19489 Does that cover the problem you were running into there?

As for `ion-back-button`, could I ask you to create an issue over on the Framework repo with a minimal reproduction app? https://github.com/ionic-team/ionic-framework/issues/new/choose

Setting LTR vs. RTL is done by setting the `dir` attribute on the `<html>` tag to either `'ltr'` or `'rtl'`. The browser or device should also automatically detect this based on the user's set language. This is the same as any web page, which is why we don't have it documented since there isn't any Ionic-specific behavior.

**Comment by FranciskoNeves** [comment] 2023-03-13 17:15
About the ion-menu, yes is that the problem.

Ok, I will create an issue about the ion-back-button

**Comment by amandaejohnston** [comment] 2023-03-13 17:26
Okay, excellent. Am I good to close this issue, or did you have any other concerns I could address?

**Comment by FranciskoNeves** [comment] 2023-03-13 17:39
Yes you can close

**Comment by amandaejohnston** [comment] 2023-03-13 17:44
Thank you, let me know if I can help with anything else here.

**Closed by amandaejohnston** 2023-03-13 17:44 UTC
Labels: triage
