### ISSUE TITLE
Code in "gallery app" tutorial causes error

### ISSUE THREAD

**Issue by nikita-fuchs** [ionic-team/ionic-docs#1169] opened 2020-01-12 14:24 UTC
**Describe the bug**
A piece of the example code of the Gallery App tutorial causes an error.

**To Reproduce**
1. Go to https://ionicframework.com/docs/angular/your-first-app/2-taking-photos
2. Do  
```
 const capturedPhoto = await Camera.getPhoto({
        resultType: CameraResultType.Uri,
        source: CameraSource.Camera,
        quality: 100
    })
``` 
and then run ```ionic serve --devapp```
3. Press the floating action button to take a picture, calling ```
photoService.addNewToGallery() ```
4. See error : 
```
"Cannot read property 'enumerateDevices' of undefined"
```

**Expected behavior**
The App would ask you to pick a photo or take a new one.

**Browser and OS (please complete the following information):**
 - OS: Android 8

**Additional context**
Works flawlessly on desktop. Here is the full code of the photo service: https://pastebin.com/tTdnGnd4

**Comment by nikita-fuchs** [comment] 2020-01-12 21:36
May it have something to do with the app not being served via https (which would be the default case when trying to write a first app and not running a build server yet) ? See https://github.com/ionic-team/capacitor/issues/1577#issuecomment-496279771

**Comment by nikita-fuchs** [comment] 2020-01-13 10:28
I found a solution: 

Requesting the camera requires an HTTPS connection to the app, which is of course not given when building your first ionic app with capacitor, therefore the tutorial is not so suitable anymore compared to the good ol' cordova times. Just building the application and running it in Android Studio still made it rely on the application being at some url defined in the `capacitor.config.json` . I had to remove the `url` there to make the app finally load locally, when running it in android studio. Here is the project, if anyone wants to give it a try: 

https://mega.nz/#!ZNUBAKTA!9muf2XmX4p2VidRgC3YmMueCoggkiRfq3ov9MoW6BOQ

**Comment by dotNetkow** [comment] 2020-01-13 21:36
Howdy! We just launched this guide a couple of days ago, and I appreciate your feedback. Some thoughts:
- As of Jan 1st, we [sunset DevApp](https://ionicframework.com/docs/appflow/devapp). It was Cordova only, so it won't work with Capacitor and thus, this guide.
- Our recommendation going forward is native tooling, like you used: Android Studio to build/deploy the app. 

If I understand correctly, you ran `ionic serve --devapp` then put the URL it gave you into the capacitor config file, then deployed and ran the app on an Android device, yes? That URL is HTTP, so correct, that also won't work.

You do have an option to run the app locally though - see the [Live Reload page](https://ionicframework.com/docs/angular/your-first-app/7-live-reload), the last one of the guide.

**Comment by nikita-fuchs** [comment] 2020-01-14 12:04
Hey, yeah by now I figured out devapp will be discontinued - actually a shame, business-wise it was a great opportunity to showcase something to a client real quick. It allowed for quicker iterations, too. (Also, devApp is a nice alternative in third world countries, where Android Studio and Emulators are just no option on local hardware. ) Originally, why many people like me who abandoned app development long time ago because of the messy cumbersomeness of Android Studio and Xcode, turned to Ionic, is that it does the platform-specific heavy lifting for you and keeps you away from the gruesome mess of the native editors. My trainees being new to development really embrace this fact 😉Let's hope Ionic will turn back to the old path, away from native tooling, one day.

Regarding the issues, there are actually two: 

1. No, I didn't put a url into the capacitor config file. I had to actually **remove ** it from there to be able to run/build the app in android studio, or else he would always try to fetch the app from the URL.

2. During live reload, the app is fetched from a non-HTTPS URL, in which case accessing the media devices (camera, etc.) [is blocked](https://github.com/ionic-team/capacitor/issues/1577#issuecomment-496279771). I guess you wrote that tutorial using a build server?

**Comment by dotNetkow** [comment] 2020-01-14 14:19
Appreciate the honest feedback - it's a decision we didn't make lightly. While DevApp was nice to get started, we found that it didn't set developers up for long term success. The reality is that at some point, if you're building a serious app, you need to use the native tooling. Cordova and config.xml provide a nice abstraction, but as soon as something goes wrong (and it will! the nature of software development) it's confusing/challenging to figure out where the issue is. By embracing native tools, issues are much easier to figure out/google for. 

Also, you may not have to really use them much, beyond building/signing an app! When plugins work, they just work like before. That's why I designed this tutorial - to showcase how easy it is: build the app, open android studio or xcode, then press Play.

Back to this specific issue: if you run the commands on the [Live Reload page](https://ionicframework.com/docs/angular/your-first-app/7-live-reload) exactly (not ionic serve devapp), it's still blocked? I tested all 3 platforms, but it's possible I missed something, of course. I'll retest Android again today.  Thanks for your patience and feedback!

**Comment by dotNetkow** [comment] 2020-01-14 20:24
OK - retested Android and I saw the behavior you described. You were correct - the external flag was needed. I merged your PR for that. Thanks a ton!

**Closed by dotNetkow** 2020-01-14 20:24 UTC
Labels: bug

**Comment by nikita-fuchs** [comment] 2020-01-14 23:38
You're welcome, thanks for reviewing !

But still one thing remains: Even if (or especially when) serving through `--external` , the media devices can't be reached and thus the tutorial doesn't work yet, because a HTTPS connection is required.
