### ISSUE TITLE
ion-datetime jump to previous month after select time

### ISSUE THREAD

**Issue by thomasyu929** [ionic-team/ionic-docs#2416] opened 2022-06-23 07:41 UTC
**Describe the bug**
in ion-datetime if you select time when you are in current month. (For example today is Jun. 23th)
then close the time picker. the month will auto jump to May. but the selected date not change just UI glitch.

**To reproduce**
1. Go to Date Time component.
2. Select time in current month. (only happens on today's month)
3. Close time picker
4. You will see jump to last month.

**Expected behavior**
Please Fix this. not switch month.

**Screenshots**
![image](https://user-images.githubusercontent.com/43472214/175243617-a1165501-52c0-4fff-8a68-d845035f6654.png)
![image](https://user-images.githubusercontent.com/43472214/175243657-768263e3-c3f0-4fe7-87f2-d067ab11a1ff.png)
![image](https://user-images.githubusercontent.com/43472214/175243704-b8c76fb1-b71b-4816-ae19-f65cdb9f092a.png)

**Browser and OS (please complete the following information)**
 - OS: [Mac BigSur]
 - Browser: [Chrome]
 - Version: [ionic/angular6.1.8]

**Comment by liamdebeasi** [comment] 2022-10-07 13:45
Hey there,

Apologies for the delay. I'm not able to reproduce this issue anymore, so I believe this was fixed. I am going to close this but let me know if you have any additional questions. Thanks!

**Closed by liamdebeasi** 2022-10-07 13:45 UTC
Labels: triage
