### ISSUE TITLE
[ionic vue] Add documentation how to include styles

### ISSUE THREAD

**Issue by joshas** [ionic-team/ionic-docs#197] opened 2018-11-26 21:29 UTC
Following ionic/vue readme I got app working, but main styles (typography, layout, etc.) were missing. Had to include `<style src="@ionic/core/css/ionic.bundle.css"></style>` in App.vue to get everything working correctly.
Would be nice to include correct way of adding styles in readme.

**Comment by brandyscarney** [comment] 2019-03-06 20:32
Thank you for the issue! I am going to close this as a duplicate of https://github.com/ionic-team/ionic-docs/issues/54 and I'll add a comment to make sure this way is included.

**Closed by brandyscarney** 2019-03-06 20:32 UTC
Labels: content, vue
