### ISSUE TITLE
ion-picker documentation is too scarce

### ISSUE THREAD

**Issue by cmer4** [ionic-team/ionic-docs#1188] opened 2020-01-16 15:38 UTC
https://ionicframework.com/docs/api/picker

Basically the doc is super limited and to understand the component one has to refer source code.
We need to update it as ion-picker is a too powerful component to neglect it:)

Happy to make pull request to do the first pass but just not sure where current documentation is stored.

**Comment by brandyscarney** [comment] 2020-01-29 17:23
Thanks for the issue! I'm going to close this as a duplicate of https://github.com/ionic-team/ionic-docs/issues/711

If you'd like to work on updating the docs for this, the documentation for all API components is in the [ionic repository](https://github.com/ionic-team/ionic).

Contributing guide: https://ionicframework.com/docs/building/contributing
Steps to update documentation: https://ionicframework.com/docs/building/contributing#modifying-documentation

Here's an example of the Datetime usage folder: https://github.com/ionic-team/ionic/tree/master/core/src/components/datetime/usage

Please let me know if you have any questions, thank you!

**Closed by brandyscarney** 2020-01-29 17:23 UTC
Labels: content

**Comment by cmer4** [comment] 2020-01-30 20:26
yep thank you, I will write down the document and submit PR later this week
