### ISSUE TITLE
ion-avatar beta docs - example image avatar.svg is not loading

### ISSUE THREAD

**Issue by chsami** [ionic-team/ionic-docs#259] opened 2019-01-04 16:22 UTC
When visiting the beta docs on https://beta.ionicframework.com/docs/api/avatar/ the image on the docs is not loading.

Browser: Chrome Version 71.0.3578.98 (Official build) (64-bits)

**Comment by brandyscarney** [comment] 2019-02-23 21:40
Closing as duplicate of https://github.com/ionic-team/ionic-docs/issues/262, thanks!

**Closed by brandyscarney** 2019-02-23 21:40 UTC
