### ISSUE TITLE
"Your First Ionic App: Vue" uses `@capacitor/storage`, which was renamed in Capacitor 4

### ISSUE THREAD

**Issue by nss-ysasaki** [ionic-team/ionic-docs#2510] opened 2022-08-26 03:05 UTC
**URL**
https://ionicframework.com/docs/vue/your-first-app

**What is missing or inaccurate about the content on this page?**

This tutorial relies on `@capacitor/storage`, which was 
renamed to `@capacitor/preferences` (as per https://github.com/ionic-team/capacitor/issues/5841#issuecomment-1213027643).

It needs to be updated accordingly; following the instructions of the tutorial word-by-word leads to https://github.com/ionic-team/capacitor/issues/5841.

**Comment by jcesarmobile** [comment] 2022-08-30 22:00
Duplicate of https://github.com/ionic-team/ionic-docs/issues/2491

**Closed by jcesarmobile** 2022-08-30 22:00 UTC
Labels: content
