### ISSUE TITLE
Dead links in select API doc

### ISSUE THREAD

**Issue by manu2504** [ionic-team/ionic-docs#1395] opened 2020-04-30 18:40 UTC
**URL**
https://ionicframework.com/docs/api/select#interface-options

**What is missing or inaccurate about the content on this page?**
The 3 links to API docs are dead

**Comment by liamdebeasi** [comment] 2020-04-30 19:32
Thanks, I am going to close this as a duplicate of https://github.com/ionic-team/ionic-docs/issues/1278.

**Closed by liamdebeasi** 2020-04-30 19:32 UTC
Labels: content
