### ISSUE TITLE
Ion item's CSS custom properties not up-to-date

### ISSUE THREAD

**Issue by manu2504** [ionic-team/ionic-docs#1513] opened 2020-06-28 16:54 UTC
**URL**
https://ionicframework.com/docs/api/item#css-custom-properties

**What is missing or inaccurate about the content on this page?**
Using the CSS custom property `--background-hover` does not have any effect when hovering the element with the mouse.
Any reason to that?

**Comment by brandyscarney** [comment] 2023-04-14 16:26
Thank you for the issue! I know this is a late reply but I don't want to close it without providing an explanation.

The `--background-hover` has a built-in opacity for each mode. Both `ios` and `md` set the `--background-hover-opacity` CSS property to `0.04` by default. If you are only changing the value of `--background-hover` you may not notice the color change if it is a small change. If you would like to change the background color on hover to a solid color, you will want to set the opacity to `1`, like the following:

```css
ion-item {
  --background-hover: red;
  --background-hover-opacity: 1;
}
```

Here is a StackBlitz example, if you comment out the `--background-hover-opacity: 1;` you can see how subtle the hover color is: https://stackblitz.com/edit/unnh7b?file=index.html

I am going to close this since the property is working as intended but please let me know if I am missing anything. Thank you!

**Closed by brandyscarney** 2023-04-14 16:26 UTC
Labels: triage
