### ISSUE TITLE
Demo source like in ionic 3

### ISSUE THREAD

**Issue by pookdeveloper** [ionic-team/ionic-docs#686] opened 2019-05-08 13:48 UTC
Put link for demo source like in ionic3, or there are a repo that contains this ?

![image](https://user-images.githubusercontent.com/3384734/57380168-c2e8ec80-71a8-11e9-93fe-712eb21cf6d2.png)

Thanks

**Comment by brandyscarney** [comment] 2019-06-24 21:23
Thanks for the issue! This repo has the demo source: https://github.com/ionic-team/ionic-docs/tree/master/src/demos/api. Leaving this open to discuss adding the demo source link. 🙂

**Comment by rtpHarry** [comment] 2019-06-26 05:25
Duplicate of #670

**Closed** 2019-07-03 07:17 UTC
Labels: feature
