### ISSUE TITLE
Hardware Back Button - Important condition for using default handlers missing

### ISSUE THREAD

**Issue by maljac** [ionic-team/ionic-docs#2217] opened 2022-03-09 19:46 UTC
**URL**
https://ionicframework.com/docs/developing/hardware-back-button#internal-framework-handlers

**What is missing or inaccurate about the content on this page?**

[Here](https://github.com/ionic-team/ionic-framework/blob/e4ec572043e22bd2626dbcfd204fc22a7335282c/core/src/utils/overlays.ts#L274) the `backdropDismiss` is used as condition for registering the back button handler for closing the modal.

I suggest to make a note in the documentation that mentions this requirement.

**Comment by amandaejohnston** [comment] 2023-02-16 20:49
Thank you for the issue. I'm going to close this as a duplicate of https://github.com/ionic-team/ionic-docs/issues/1498.

**Closed by amandaejohnston** 2023-02-16 20:49 UTC
Labels: triage
