### ISSUE TITLE
Component demos load slowly because of lazy loading

### ISSUE THREAD

**Issue by imgx64** [ionic-team/ionic-docs#376] opened 2019-01-30 11:47 UTC
Loading the demos for Ionic components is very slow, taking about 8 seconds on my PC (See below image). This gives a very bad first impression to new users, who will be worrying that their PWAs will also load slowly.

I think the issue is lazy loading, and some chunks don't start downloading until after previous chunks are parsed. Furthermore, some demos (like ion-action-sheet) will only load the modal part after the user clicks the button. This gives the impression that the app itself is slow to respond to user clicks.

The solution could be either (or both):
1- Disable lazy loading for the docs demos.
2- Fix lazy loading to be more coarse grained and load whole pages at once.

![image](https://user-images.githubusercontent.com/318668/51978955-ca5b7400-249c-11e9-9895-5ef7cff8feab.png)

**Comment by adamdbradley** [comment] 2019-02-02 13:00
The issue isn't directly related to lazy loading, and the demo app itself has room for improvements. Additionally, upcoming versions of stencil will allow us to do better module preloading. Going to close this since it'll be continuous improvements.

**Closed by adamdbradley** 2019-02-02 13:00 UTC
