### ISSUE TITLE
content: Ionic build command is for version 3

### ISSUE THREAD

**Issue by ptmkenny** [ionic-team/ionic-docs#2784] opened 2023-02-22 00:06 UTC
### URL

https://ionicframework.com/docs/v3/cli/build/

### Issue Description

When I searched Google for "ionic build command", this is the first result.  It seems this page is for v3 of Angular, but there is no statement that this is outdated, and there is no link to updated info.

This is a  problem because the current version of Ionic build has completely different commands.

For example, when I run `ionic help build` on my machine, I get the following:

```
 ionic build - Build web assets and prepare your app for any platform targets

    ionic build will perform an Ionic build, which compiles web assets and prepares them for deployment.
    
    This command will convert options to the environment variables used by React Scripts. See the create-react-app
    docs[1] for explanations.
    
    [1]: https://facebook.github.io/create-react-app/docs/advanced-configuration

  Usage:

    $ ionic build [options]

  Options:

    --public-url=<url> .............. [react-scripts] The URL at which the app will be served
    --ci ............................ [react-scripts] Treat warnings as build failures, test runner does not watch
    --no-source-map ................. [react-scripts] Do not generate source maps
    --no-inline-runtime-chunk ....... [react-scripts] Do not include the runtime script in index.html (import instead)

  Advanced Options:

    --engine=<engine> ............... Target engine (e.g. browser, cordova)
    --platform=<platform> ........... Target platform on chosen engine (e.g. ios, android)

  Examples:

    $ ionic build 
```

These options are not described on the linked page, and in some cases they are opposite. (--source-map vs --no-source-map)

**Comment by jstjnsn** [comment] 2023-05-26 09:25
There already is updated documentation for the build command: https://ionicframework.com/docs/v6/cli/commands/build. I found this page by searching for "build" on the ionic docs homepage search bar. If I search for "ionic build command" on google the second result is https://ionicframework.com/docs/cli/commands/build which is the correct result. @ptmkenny Maybe you can try to search google again in a private browsing window to see if you get different results. Maybe your algorithm things you are looking for v3 build commands because you searched for them in the past.

**Comment by brandyscarney** [comment] 2024-07-26 20:59
I am going to close this as I am unable to reproduce this now. If you are still seeing this please create a new issue. Thank you!

**Closed by brandyscarney** 2024-07-26 20:59 UTC
Labels: bug, feature request
