### ISSUE TITLE
App Center Analytics - Formatting error in VS Code tooltip

### ISSUE THREAD

**Issue by rtpHarry** [ionic-team/ionic-docs#737] opened 2019-06-09 11:46 UTC
**Describe the bug**
Sorry, a bit of a lazy bug report here but I'm busy coding and don't have time to deep dive to figure out what it is or where it should be reported.

![image](https://user-images.githubusercontent.com/1038062/59158603-f6dc6800-8aee-11e9-98fe-905137292185.png)

**To Reproduce**
1. Install as outlined here: https://ionicframework.com/docs/native/app-center-analytics
2. Get the tooltip up like the screenshot by hovering over `AppCenterAnalytics` class reference
3. Scroll tooltip down until you see the screenshot

Seems like there is some formatting inserted that isnt being parsed. Not sure if if this is vscode or even this repo but suspect its a typo in the related package somewhere. Looks like its trying to bold it?

**Expected behavior**
Clean formatting.

**Browser and OS (please complete the following information):**

**Additional context**

**Comment by jcesarmobile** [comment] 2022-06-17 09:03
The tooltip comes from ionic-native repository (now https://github.com/danielsogl/awesome-cordova-plugins repository).
The text looks good there, not sure if it was fixed or if the problem is on vs code.
Closing since it has nothing to do with ionic docs.

**Closed by jcesarmobile** 2022-06-17 09:03 UTC
Labels: bug, structural
