### ISSUE TITLE
RESULT_CODE_UNINSTALL_USER_CANCEL

### ISSUE THREAD

**Issue by muuvmuuv** [ionic-team/ionic-docs#1359] opened 2020-04-14 08:19 UTC
**Describe the bug**

When visiting "https://ionicframework.com/docs/api/datetime", the latest Microsoft Edge browser (chromium) gives me this error after scrolling.

**To reproduce**
1. Go to 'https://ionicframework.com/docs/api/datetime'
3. Scroll

**Expected behavior**

No error.

**Screenshots**

![Bildschirmvideo aufnehmen 2020-04-14 um 10 15 56](https://user-images.githubusercontent.com/11534760/79202061-4e4b1300-7e39-11ea-8060-38f032035312.gif)

**Browser and OS (please complete the following information)**
 - OS:  macOS 10.15.4 
 - Browser: Microsoft Edge
 - Version: 81.0.416.53

**Additional context**

**Comment by gquittet** [comment] 2020-04-17 11:55
Same issue here with a project that use stencil.

**Comment by Gioni06** [comment] 2020-06-03 12:43
Any idea why this happens? I have a similar issue with a project using LitElement

**Comment by ashishneosofttech** [comment] 2020-07-18 17:26
Same here...
When using youtube on ubuntu 18.04 on chrome browser

**Comment by TheGitPanda** [comment] 2020-08-13 10:11
I have a similar issue with a React project in Chrome 84.0.4147.125

However I have a feeling it could be to do with memory/ garbage collection. I had a look at the memory tab in Dev Tools and noticed my app increasing by ~2mb each time. Not sure if this really has an effect to show this message but its the only explanation I can think of so far.

In my case Im not destroying my React components properly at root level. (Please dont judge, as its the way my project is but Im using PHP to render the page content then running a component loader to load `<react-component name="EditorPage"></react-component>`. So when I load another request from PHP, the `componentWillUnmount()` method is possibly not being called hence adding to memory and causing a crash. A hard reload helps to clear this message. Just thought Id throw this out..

**Comment by jcesarmobile** [comment] 2022-06-17 10:17
I can't reproduce on latest edge, might have been fixed on edge or on the docs. 
Closing since there has been no comments about it on the last 2 years, so it's probably not an issue anymore.

**Closed by jcesarmobile** 2022-06-17 10:17 UTC
Labels: bug
